title: THRIVE Lifeline Homepage
description: The homepage for THRIVE Lifeline a crisis text line for marginalized individuals in STEM

#baseurl: /
color-scheme: "#68368D" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _data

exclude:
  - .sass-cache

plugins:
  - jekyll-redirect-from
  # - jekyll-target-blank

# target-blank:
#     css_class: ext-link

## User-Defined Definitions to make less HTML changes
# For "HOME" return link and copyright
org_name: T.H.R.I.V.E. Inc.

# For header on home page
group_name: THRIVE Lifeline

group_description: "<b>T</b>hriving <b>H</b>arnesses <b>R</b>espect,
<b>I</b>nclusion, and <b>V</b>ested <b>E</b>mpathy: A crisis text line for
marginalized individuals in STEM."

# Copyright year
cr_year: 2020

crisis_phone: +1 (313) 662-8209
contact_email: info@thrivelifeline.org

# Social Media Accounts (NO AT SYMBOL)
Twitter: thrivelifeline
Instagram: thrivelifeline
