---
title: "About THRIVE"
output:
  html_document:
    toc: true
    toc_float: true
---

**T**hriving **H**arnesses **R**espect, **I**nclusion, and **V**ested
**E**mpathy: A text-based crisis line staffed by people in STEMM with marginalized
identities.

THRIVE Lifeline is a 501(c)(3) grassroots organization dedicated to
changing the landscape of mental health support for people with 
intersecting marginalized identities. Among our services, we offer a free 
text-based crisis line. We are led by experienced crisis managers who 
are fed up with watching our communities fall prey to systemic 
marginalization only to face dismissive, unsupportive, and sometimes 
dangerous interactions through traditional mental health avenues. 
Since opening in June 2020 we have served texters in all 50 U.S. 
states and Puerto Rico. all Canadian provinces, and almost 50 additional 
countries worldwide.


We take a different approach. When you text THRIVE Lifeline, you can rest assured that our goal is to create the space you need to feel heard, valued, and uplifted. YOU, not your crisis, are at the center of our conversation. As a 988 alternative, we do not engage in non-consensual active rescue and want to respect your own decisions and autonomy. For our full policies, click [here](https://thrivelifeline.org/images/privacy.pdf).

Our Crisis Responders all have at least one marginalized identity and are rigorously trained using our proprietary curriculum, taught by and for people with intersecting marginalized identities. We hope that when you reach out to THRIVE you will talk to someone who gets it. 

<br>

## Who Are We?
THRIVE Lifeline is Trans-led and operated. We are a volunteer run and operated group of certified suicide interventionists whose identities are marginalized, and who are students, career professionals, and retirees largely trained across the breadth of STEMM fields

<style>
    .caption {
        display:none;
    }
</style>

```{r, echo=FALSE, message=FALSE, fig.align="center", fig.cap="Barplot of the identities of the THRIVE Lifeline team. LGBTQ2S+ makes up 80%, people of color make up 63%, people with disabilities make up 54%, trans people make up 40%, and immigrants make up 19%."}
## Use fig.cap to set up caption/alt text. The CSS directly above will silence 
## The caption

## Reset margins c(bottom, left, top, right)
## Default is c(5.1, 4.1, 4.1, 2.1)
par(mar=c(6,4,4,10), xpd=TRUE)

## Set up colors
colors = c("#65427D", "#FAF4A0") #"#58A4AF", "#EF8254", "#C2C8E5", "#AC8FC0")

# Trait = c(yes, no)
LGBTQ = c(89, 11)
Disability = c(66, 34)
POC = c(58, 42)
Nonbinary  = c(40,60)
#International = c(29,71)
Immigrant = c(16, 84)

## Create a dataframe with all of these for plotting
traits = data.frame(LGBTQ, Disability, POC, Nonbinary, Immigrant)

## Transform the data into %
traits_percentage <- apply(traits, 2, function(x){x*100/sum(x,na.rm=T)})

## Make a barplot
barplot(traits_percentage,             ## Use percentage data
        col=colors,                    ## Use colors from above
        main="THRIVE's Team",          ## Title Name
        border="white",                ## Border color for the boxes
        ylab="Percentage",             ## Y-axis label
          ## Name the datasets; \n is a linebreak
        names.arg=c("LGBTQ2S+", "People with\nDisabilities", "People of\nColor", 
                    "Nonbinary", "Immigrants"), 
        legend=c("Yes"),               ## Legend Label
        las=2,                         ## Turn x-axis 90º
          ## Force legend outside the plot
          ## bty is the box around legend (yes = o, no = n)
        args.legend = list(x ='right', bty='o', inset=c(-0.18,0))
        )
```

<br>
Our backgrounds include surviving suicide and trauma, familial rejection due to our identities, food and housing insecurity, poverty, lack of access to education, immigration, and more. We navigate disabilities, dissociation, PTSD, and other mental health needs and neurodivergencies. We personally live and understand chronic marginalizing experiences.


Want to learn more about THRIVE and what it means to our president? Check out this [Genderful podcast episode](https://youtu.be/UnKQPcblgyE).

<br>

## Mission
THRIVE Lifeline’s mission is to end stigma for people with marginalized 
identities and close gaps in access to crisis intervention, validation, and 
resources through whole-human support.

We fulfill our mission by:

* Providing texters with free 24/7/365 hotline support by trained, non-carceral Crisis Responders who share marginalized identities and backgrounds.
* Normalizing suicidality and depathologizing stigmatized mental health experiences through whole-human practices that provide life-saving and life-affirming support.
* Combining lived experience with anonymized data to advocate for systemic changes and provide exhaustive training through a non-carceral lens.

<br>

## Vision
We envision a world where the response to someone in crisis is to pause to ask what safety looks like to them and what systemic barriers they might be facing, getting to know the whole human prior to ushering in non-consensual help.

<br>

## Core Values

* Accessibility: THRIVE Lifeline remains 100% free to texters.
We believe that access to life-affirming and life-saving resources is crucial.
* Connection: Often, our texters are ‘the only one’ in their families, in their
departments, in their labs, in their classrooms.
When a texter reaches out to THRIVE Lifeline, they are not alone.
* Inclusion: Representation matters.
Being recognized at the core of who you are is the center of inclusion.
Whoever you are, wherever you are from, THRIVE welcomes you.
* Integrity: We uphold the highest standards of communications, support, and
confidentiality, knowing that the heart of our work involves people at their
most vulnerable times.

<br/>

<center>
<p style="font-size:16pt; font-weight: bolder">We believe that it is together 
that we THRIVE.</p>
</center>

We need your help in order to keep THRIVE Lifeline as a vital resource!
You can help by **volunteering, donating**, and **sharing**.

- **Volunteer**: Learn more at our [volunteer information](volunteer.html) page.
<br/>
- **Donate**: Your donations of any size help to save and affirm lives. Currently we are are raising operational funds and funds to support our RECRUIT internship program. 
   - <a href=https://www.facebook.com/THRIVELifeline><b>
Facebook</b></a>
   - <a href=https://www.paypal.com/donate?hosted_button_id=CU5D6Q727QH5S><b>
Paypal</b></a> (@THRIVELifeline)
   - <a href=https://venmo.com/code?user_id=3676112202761290213><b>
Venmo</b></a> (@THRIVELifeline)
   - <b>Check:</b> <u>Make out to:</u> THRIVE Inc.  <u>Mail to:</u> 2114 N. Flamingo Rd. Box #5018; Pembroke Pines, FL 33028
- **Share**: If you or anyone that you know is in need of support, THRIVE
Lifeline is providing 100% confidential, judgment-free text-based support at
<a href="sms:+13136628209&body=THRIVE">**+1.313.662.8209**</a>

<br>

<center>
<p style="font-size:16pt; font-weight: bolder">Please be advised that our text 
line supports individuals 18+.</p>
</center>

If at any time you would like to stop a text-based conversation, please text STOP.
Conversations are 100% confidential.

<br>

## Under 18?

For general support, please reach out to
[**Boys Town National Hotline**](https://www.boystown.org/hotline/Pages/default.aspx).
Despite the name, this hotline is for people of all genders.

* 24/7 call-based support:
   + <a href="tel:+18004483000">+1.800.448.3000</a>.
* Text-based support:
   + Text VOICE to <a href="sms:20121&body=VOICE">20121</a>.

For LGBTQ2S+ support, please reach out to
[**The Trevor Project**](https://www.thetrevorproject.org/).

* 24/7 call-based support:
   + <a href="tel:+18664887386">+1.866.488.7386</a>.

* Text-based support:
   + Text START to <a href="sms:678678&body=START">678-678</a>.
