---
title: "THRIVE Reading List"
output:
  html_document:
    toc: true
    toc_float: true
---

### Navigating Academia and the Workplace
* *A Black Woman's Guide to Earning a Ph.D.: Surviving the First 2 Years* 
by Nicole A. Telfer,
[ISBN: 9781664130036](https://www.goodreads.com/book/show/56301865-a-black-woman-s-guide-to-earning-a-ph-d)
* *Academic Ableism: Disability and Higher Education* by Jay T. Dolmage,
[ISBN: 9780472053711](https://www.goodreads.com/book/show/35069841-academic-ableism)
* *Black STEM USA: America's Next Civil Rights Movement* by C.M. Williams and 
Sharon Ewell Foster, [ISBN:9780996870702](https://www.goodreads.com/book/show/31448244-black-stem-usa)
* *Decolonizing Academia: Poverty, Oppression and Pain* by Clelia O. Rodríguez,
[ISBN: 9781773630748](https://www.goodreads.com/book/show/40249837-decolonizing-academia)
* *Hooded: A Black Girl’s Guide to the Ph.D.* by Malika Grayson,
[ISBN: 9781953307](https://www.goodreads.com/book/show/55598728-hooded)
* *Our Doctoral Journey: A Collection of Black Women's Experiences* 
by Nicole A. Telfer,
[ISBN: 9781669827092](https://www.goodreads.com/book/show/61238612-our-doctoral-journey)
* *Surviving Your Stupid Stupid Decision to Go to Grad School* by Adam Ruben,
[ISBN: 9780307589446](https://www.goodreads.com/book/show/7769479-surviving-your-stupid-stupid-decision-to-go-to-grad-school)
* *Twice as Hard: The Stories of Black Women Who Fought to Become Physicians, 
from the Civil War to the Twenty-First Century* by Jasmine Brown,
[ISBN: 9780807025086](https://www.goodreads.com/book/show/61022944-twice-as-hard)

### STEMM-Focused
* *The Disordered Cosmos: A Journey into Dark Matter, Spacetime, and 
Dreams Deferred* by Dr. Chanda Prescod-Weinstein,
[ISBN: 9781541724709](https://www.goodreads.com/en/book/show/54455629-the-disordered-cosmos)

### Academic Fiction
* *Real Life* by Brandon Taylor,
[ISBN: 9780525538882](https://www.goodreads.com/book/show/46263943-real-life)
* *Transcendent Kingdom* by Yaa Gyasi, 
[ISBN: 9780525658184](https://www.goodreads.com/book/show/48570454-transcendent-kingdom)

### Workbooks and Mental Health Books
* *Managing Your Mind: The Mental Fitness Guide* by Gillian Butler,
[ISBN: 9780195314533](https://www.goodreads.com/book/show/883834.Managing_Your_Mind)
* *The Unapologetic Guide to Black Mental Health: Navigate an Unequal System, 
Learn Tools for Emotional Wellness, and Get the Help you Deserve* by Rheeda Walker, 
[ISBN: 9781684034147](https://www.goodreads.com/book/show/51043956-the-unapologetic-guide-to-black-mental-health)
* *The Queer and Transgender Resilience Workbook* by Anneliese A. Singh,
[ISBN: 9781626259461](https://www.goodreads.com/book/show/33776101-the-queer-and-transgender-resilience-workbook)
* *The Gender Quest Workbook: A Guide for Teens and Young Adults Exploring
Gender Identity* by Rylan Jay Testa, Deborah Coolhart, and Jayme Peta,
[ISBN: 9781626252974](https://www.goodreads.com/book/show/23845906-the-gender-quest-workbook)
* *The Reflective Workbook for Partners of Transgender People: Your Transition
as Your Partner Transitions* by D.M. Maynard,
[ISBN: 9781785927720](https://www.goodreads.com/book/show/43610689-the-reflective-workbook-for-partners-of-transgender-people)

### Affirming Religious Texts
* *The Black Trans Prayer Book* co-edited by J Mase III and Lady Dan Figueroa 
Edidi, [ISBN: 9781678197612](https://theblacktransprayerbook.org/)
* *God and the Gay Christian* by Matthew Vines, 
[ISBN: 9781601425164](https://www.goodreads.com/book/show/17934778-god-and-the-gay-christian)
* *Transforming: The Bible & the Lives of Transgender Christians* by Austen Hartke, 
[ISBN: 9780664263102](https://www.goodreads.com/book/show/36234500-transforming)
  * Translation in Spanish: [*TransFormadxs: La Biblia y las Vidas de lxs 
  Cristianxs Transgénero*](http://austenhartke.com/book)
* *Walking the Bridgeless Canyon: Repairing the Breach Between the Church and 
the LGBT Community* by Kathy Baldock,
[ASIN: B00OBXN80G](https://www.goodreads.com/book/show/23367214-walking-the-bridgeless-canyon)
* *We Have Always Been Here: A Queer Muslim Memoir* by Samra Habib,
[ISBN: 9780735235007](https://www.goodreads.com/book/show/43383506-we-have-always-been-here)

### Children's and Illustrated Books
* *The Secret Lives of Scientists, Engineers, and Doctors: Volume 1* by Faisal
Hossain, 
[ISBN: 9781645434450](https://mascotbooks.com/mascot-marketplace/buy-books/childrens/picture-books/the-secret-lives-of-scientists-engineers-and-doctors-volume-1/)
* *Introducing Teddy: A Gentle Story About Gender and Friendship* by Jess Walton
and illustrated by Dougal MacPherson, 
[ISBN: 9781681192109](https://www.goodreads.com/book/show/27158837-introducing-teddy)
* *When Aidan Became A Brother* by Kyle Lukoff and illustrated by Kaylani
Juanita, 
[ISBN: 9781620148372](https://www.goodreads.com/book/show/39987021-when-aidan-became-a-brother)
* *It Feels Good to Be Yourself: A Book About Gender Identity* by Theresa Thorn
and illustrated by Noah Grigni, 
[ISBN: 9781250302953](https://www.goodreads.com/book/show/40864913-it-feels-good-to-be-yourself)

### LGBTQ+ YA Fiction
*  *I am J* by Cris Beam,
[ISBN: 9780316053617](https://www.goodreads.com/book/show/8140535-i-am-j)
* *Beautiful Music fo Ugly Children* by Kirstin Cronn-Mills,
[ISBN: 9780738732510](https://www.goodreads.com/book/show/13221769-beautiful-music-for-ugly-children)
* *Huntress* by Malinda Lo,
[ISBN: 9780316040075](https://www.goodreads.com/book/show/9415946-huntress)
* *Will Grayson, Will Grayson* by John Green and David Levithan,
[ISBN: 9780525421580](https://www.goodreads.com/book/show/6567017-will-grayson-will-grayson)
* *Little & Lion* by Brandy Colbert,
[ISBN: 9780316349000](https://www.goodreads.com/book/show/25062038-little-lion)
* *Felix Ever After* by Kacen Callender,
[ISBN: 9780062820259](https://www.goodreads.com/book/show/51931067-felix-ever-after)
* *Stay Gold* by Tobly McSmith,
[ISBN: 9780062943194](https://www.goodreads.com/book/show/45306326-stay-gold)
* *Openly Straight* Series
    * *Openly Straight* by Bill Konigsberg (Book 1),
    [ISBN: 9780545509893](https://www.goodreads.com/book/show/16100972-openly-straight)
    * *Openly, Honestly* by Bill Konigsberg (Book 1.5),
    [ISBN: 9781338171280](https://www.goodreads.com/book/show/34727888-openly-honestly)
    * *Honestly Ben* by Bill Konigsberg (Book 2),
    [ISBN: 9780545858267](https://www.goodreads.com/book/show/27230789-honestly-ben)
* *Simon Snow* Series
    * *Carry On* by Rainbow Rowell (Book 1),
    [ISBN: 9781250135025](https://www.goodreads.com/book/show/32768522-carry-on)
    * *Wayward Son* by Rainbow Rowell (Book 2),
    [ISBN: 9781250146076](https://www.goodreads.com/book/show/44017627-wayward-son)
    * *Any Way the Wind Blows* by Rainbow Rowell (Book 3; Anticipated 2021),
    [ISBN: 9781250254337](https://www.goodreads.com/book/show/52190991-any-way-the-wind-blows)

### Anti-Racist Literature
* *Black Fatigue: How Racism Erodes the Mind, Body, and Spirit* 
by Mary-Frances Winters, 
[ISBN: 9781523091300](https://www.goodreads.com/book/show/51773973-black-fatigue)
* *Caste: The Origins of Our Discontents* by Isabel Wilkerson,
[ISBN: 9780593230251](https://www.goodreads.com/en/book/show/51152447-caste)
* *The Color of Law: A Forgotten History of How Our Government Segregated America*
by Richard Rothstein,
[ISBN: 9781631492853](https://www.goodreads.com/book/show/32191706-the-color-of-law)
* *My Grandmother's Hands: Racialized Trauma and the Mending of Our Bodies and Hearts* 
by Resmaa Menakem, 
[ISBN: 9781942094470](https://www.goodreads.com/book/show/34146782-my-grandmother-s-hands)
* *So You Want to Talk About Race* by Ijeoma Oluo,
[ISBN: 9781580056779](https://www.goodreads.com/book/show/35099718-so-you-want-to-talk-about-race)
* *Superior: The Return of Race Science* by Angela Saini,
[ISBN: 9780807076910](https://www.goodreads.com/book/show/42042093-superior)
* *White Fragility: Why It’s So Hard for White People to Talk About Racism* by
Robin DiAngelo,
[ISBN: 9780807071168](https://www.goodreads.com/book/show/43708708-white-fragility)

### Non-fiction
* *The Autobiography of a Transgender Scientist* by Dr. Ben Barres,
[ISBN: 9780262039116](https://www.goodreads.com/book/show/39644215-the-autobiography-of-a-transgender-scientist)
* *Beyond Magenta: Transgender Teens Speak Out* by Susan Kuklin,
[ISBN: 9780763656119](https://www.goodreads.com/book/show/18166920-beyond-magenta)
* *The Bisexual Option* by Fred and Fritz Klein,
[ISBN: 9781560230335](https://www.goodreads.com/book/show/280893.The_Bisexual_Option)
* *Green Card Voices* a [Book Series](https://www.greencardvoices.org/store/)
* *High School* by Teagan and Sara Quin,
[ISBN: 9780374169947](https://www.goodreads.com/book/show/43197389-high-school)
* *Inferior: How Science Got Women Wrong—and the New Research That's Rewriting
the Story* by Angela Saini,
[ISBN: 9780807071700](https://www.goodreads.com/book/show/31869108-inferior)
* *Letter to a Young Female Physician: Notes from a Medical Life* by Suzanne Koven, [ISBN: 9781324007142](https://www.goodreads.com/book/show/55298407-letter-to-a-young-female-physician)
* *Raising Them: Our Adventure in Gender Creative Parenting* by Kyl Myers,
[ISBN: 9781542003681](https://www.goodreads.com/book/show/49974828-raising-them)
* *Redefining Realness: My Path to Womanhood, Identity, Love & So Much More* by 
Janet Mock, [ISBN: 9781476709123](https://www.goodreads.com/book/show/18144031-redefining-realness)
* *The Remedy: Queer and Trans Voices on Health and Health Care* edited by Zena Sharman,
[ISBN: 9781551526584](https://www.goodreads.com/book/show/29363318-the-remedy)
* *Trans\* in College: Transgender Students' Strategies for Navigating Campus
Life and the Institutional Politics of Inclusion* by Dr. Z. Nicolazzo,
[ISBN: 9781620364574](https://www.goodreads.com/book/show/30148613-trans-in-college)
* *Trans Medicine: The Emergence and Practice of Treating Gender* 
by Dr. stef m. shuster,
[ISBN: 9781479845378](https://www.goodreads.com/book/show/56217471-trans-medicine)

### Other Books
* *Invisible Storm: A Soldier’s Memoir of Politics and PTSD* by Jason Kander,
[ISBN: 9780358658962](https://www.goodreads.com/book/show/58312014-invisible-storm)
* *On Earth We're Briefly Gorgeous* by Ocean Vuong, 
[ISBN: 9780525562023](https://www.goodreads.com/book/show/41880609-on-earth-we-re-briefly-gorgeous)