---
title: "Recruiting Empathy: Crisis Responder Undergraduate Internship @THRIVE (RECRUIT)"
output:
  html_document:
    toc: true
    toc_float: true
---

<center>
<i class="fas fa-hard-hat fa-3x" aria-hidden="true"></i> Under Construction! <i class="fas fa-hard-hat fa-3x" aria-hidden="true"></i>
</center>
<br>

THRIVE’s developing internship program centers undergraduate students whose 
identities are marginalized.

\* We prioritize applications from underrepresented LGBTQ2S+ persons of color, 
persons living with disabilities, Two Spirit, trans-femme and/or 
femme nonbinary individuals, and/or veterans. 
THRIVE Lifeline is volunteer-run and fully staffed by people with diverse, 
underrepresented identities. 
We are majority POC and LGBTQ2S+ and seek to serve our communities. 

**As an all-volunteer staff, we currently do not offer paid internships.

We are currently accepting applications for internship positions for the 
2021-2022 academic year and will keep interest open for waitlist opportunities 
as positions are filled.

[Click here to submit your interest form.](https://form.jotform.com/212686020923149)
We will reply back with a formal application.

## Welcome

You may be pursuing a degree in psychology, sociology, social work, 
pre-medicine, public health, or any number of human-serving disciplines, 
and seeking an internship or practicum that will 

1. Meet you where you are as a student who experiences marginalization
2. Empower you and give you undeniable professional experience
3. Equip you with the skills to directly impact the lives of others who may share your intersecting identities and experiences.

You may be in a rural area or otherwise lack access to an identity-affirming 
internship or practicum. 
Our interns and volunteers work remotely and internationally. 
We are able to provide you support, wherever you are!

## Program

Our internship program is designed to offer a combined 120 hours 
(9 - 12 months) of crisis intervention training, professional development, 
regular connection with a mentor, and supervised crisis response on 
THRIVE Lifeline. 
Our training is centered in Whole-Human, empathetic support, cross-identity 
affirmation, trauma-informed care, and skillful deescalation.
When you are onboarded, you will be paired  with a mentor who will work 
directly with you throughout training and as you begin shifts on 
THRIVE Lifeline. 

*Please let us know if your degree program has specific requirements for*
*your mentor.*

### Training

40-50 hours of training will include:

- Professional and Interpersonal Skills
- Navigating triggering and unfamiliar topics 
- Common pitfalls in our language or responses 
- Conducting consensual and affirming risk assessments
- Being alert to signs of distress or escalation
- Affirming identity first; recognizing identities you share versus those you do not
- Awareness of individual and community trauma and its impact
- Recognizing your own trauma and building a self care routine that allows you to prioritize a texter’s needs
- Safe deescalation techniques
- Trauma-informed and accessible grounding techniques
- Affirming referrals and / or resources 
- Experiential Learning 
- Reading a variety of scenarios and learning a variety of response perspectives
- Practicing a minimum of 10 text-based scenarios where you will actively respond to a practice texter in crisis
- *Optional*: professional development specific to navigating marginalized identities and experiences in the workplace

### Crisis Response

70-80 hours of crisis response:

Once you have completed training, you will transition to being a 
Crisis Responder on THRIVE Lifeline. 
On-call shifts are 3 hours each, and interns complete 1 - 2 shifts per week. 
The Lifeline is available 24/7/365, so we seek flexible availability.

### Personal / Professional development

We understand the barriers that many in our communities face and the impacts 
to resumes, skill building, and academic training that result. 
For those who are interested, we provide additional leadership training and 
experience, opportunities to train others, contribute to curriculum 
development, learn how to operate a non-profit organization, etc. 
We provide superb references, support writing of funding applications and 
personal statements, and are dedicated to empowering you to reach your 
personal dreams!

## What we need from you
Interested interns should: 

  - Be undergraduate students
  
    - We understand that barriers to entry may mean you are interested in an 
    internship or practicum with THRIVE and not be an undergraduate student. 
    If this is true for you, please share your circumstances with us in our 
    interest form so that we may respond to your specific needs.
    
  - Be seeking an unpaid internship or practicum experience that centers people 
  with marginalized identities
  - Be 18+ years of age
  - Have reliable access to a computer with high speed internet and privacy
  - Be able to complete 120 hours (9-12 months) of internship, 
  including 40-50 hours of training and 70-80 hours of shifts as a 
  Crisis Responder on THRIVE Lifeline
  - Attend 4 live virtual trainings
  - Attend weekly one-on-one meetings with your mentor
  - Affirm all identities, especially those that are least represented
  - Be willing to work in a collaborative, supportive environment and dialogue 
  openly
  - Be willing to learn and grow through supportive and constructive feedback
  - Be willing to offer support to other volunteers, especially those who are 
  responding to texters in crisis

## How we will help you THRIVE

THRIVE interns gain:

  - 120 supported internship / practicum hours (we have some ability to 
  tailor to your academic requirements; please let us know your needs)
  - Inclusive and accessible crisis intervention training
  - Training in and exposure to a variety of marginalized identities and 
  experiences
  - Trauma-informed crisis intervention and deescalation skills
  - Confidence to support your own community
  - One-on-one weekly mentorship and a team who supports you with diverse 
  perspectives and resources when you are on THRIVE Lifeline
  - Leadership and professional development opportunities
  - Recommendation letters and assistance with graduate school, funding, 
  and / or professional applications

[Click here to submit your interest form.](https://form.jotform.com/212686020923149)
We will reply back with a formal application within 48 hours.
