---
title: "Volunteer with THRIVE"
---

Help your communities to THRIVE! We invite you to join THRIVE Lifeline's international team of volunteers and begin offering life-saving and life-affirming support. Our volunteers are students and professionals, working remotely from anywhere. When you volunteer with us, you will be provided opportunities for mentorship, skill development, and leadership growth. Whatever your passions or experience level, we have a place for you!

<br>
Volunteer with THRIVE! [**Apply Here**](https://form.jotform.com/201655418668059).
We will reply within 48 hours.

Requirements:

* 18+ years old
* Identify as an underrepresented individual
* **Peer Supporters**: Willingness to complete a minimum of 4 weeks of training. Peer Supporters commit to a minimum of 100 hours of peer support shifts with THRIVE Lifeline after their training is completed.
    + Training is a hybrid of synchronous and asynchronous readings, exercises, 
      live discussions, practices, and shadowing
    + Training must be completed in no more than 3 months
* **General Volunteers**: Willingness to complete the estimated weekly time commitment or project, as detailed below.
* Willingness to normalize stigmatized mental health experiences, challenge biases, and address pathologizing statements
* Commitment to non-carceral support and to reaching your highest potential of community care!

Note: No prior experience is necessary.

* [Stronger U](https://strongeruwellness.com/) provides complete educational programs, including personalized education, resources, coaching, and certification, to THRIVE's peer support and crisis response teams. These programs center Whole-Human, cross-identity affirmation, safer non-carceral skills, and conscientious intervention from trauma-informed and lived-experience lenses. Program certificates of completion are provided to selected applicants who complete all program elements including, initial training, ongoing education, mentorship, and skills practices, and all required shifts, while remaining in good standing as a THRIVE Lifeline volunteer.
* Volunteers can work from any location: all that is required is a computer
with reliable internet and a private space.
* Representation is at the heart of THRIVE. We encourage applications from multiply marginalized people across a breadth of identities and experiences.

<br>
THRIVE offers a variety of volunteer positions, some of which receive extensive training and mentorship and require longer term commitments from volunteers while others receive basic training and complete shorter term projects. If you are looking to provide general support without going through an application, there are a number of ways to do this as well. All THRIVE volunteers work remotely, from almost anywhere globally.

Longer term volunteer positions include: (*Full job descriptions are available in links beside each position.*)

   * **Peer Supporter**: This volunteer will support community members in our Discord server. Estimated time is approximately 5 hours per week during training, then 3 - 6 hours per week after.
     [Full Description](https://drive.google.com/file/d/1hmQR6owM7eOixeCI4kR7MwtSu6FlM8f3/view?usp=sharing)
   * **Training Assistant**:  This volunteer will support our Peer Supporter in training by acting as community members in need of support based on scripted scenarios, and then providing feedback. Estimated time is 2 hours per week
   [Full Description](https://drive.google.com/file/d/1xkAzZhHrGs4GUVIykK1xxEy6jwouxr08/view)
   * **Social Media Team Members**: This volunteer will design and create social media posts in Canva to share on THRIVE’s Instagram, Facebook, and LinkedIn pages. Estimated 4 hours per week.
        [Full Description](https://drive.google.com/file/d/1skqhjX80sC_wSPx-UnU_zRwVsCEwYD6G/view)
  * **Outreach Specialist**: This volunteer will assist with outreach, sharing
   THRIVE Lifeline as a resource and broadening the impact of the hotline. [Full Description](https://drive.google.com/file/d/1v6OnQgwzMHzAoKhpSHMTgS3Y4CSHgF4A/view?usp=drive_link)

<!--
  * **Peer Support Group Facilitator**: Volunteers to facilitate a minimum of one 1-hour peer support group per month inside our Stronger Together discord server. Our application process for peer support facilitators who are not current THRIVE volunteers includes: Submit a volunteer application and detail your interest and experience with peer support facilitation. We will connect to ask any clarifying questions and ask you to sign a volunteer agreement.  Finally, we will invite you to lead a 30 minute support group for THRIVE volunteers. We will take an additional 30 - 60 minutes within that meeting to discuss any feedback, answer any questions that you have, and complete your orientation. Please note that Peer Support Group Facilitators are covered under THRIVE Inc liability insurance and subject to all organizational policies and procedures.
    * **Assistant Volunteer Coordinator for Applications**: This volunteer will 
   manage all THRIVE volunteer applications, including communications with 
   volunteers throughout the process. 
   Estimated 6-8 hours per week, with flexible and reliable schedule.
    [Full Description](https://drive.google.com/file/d/1klrA_v1cWABNIHTN-7ui80xAhREA_dCz/view)
   * **Assistant Volunteer Coordinator for Onboarding**: This volunteer will 
   guide new THRIVE volunteers through the onboarding process, including mentor 
   connections and leading volunteer orientations. 
   Estimated 6-8 hours per week, with flexible and reliable schedule.
    [Full Description](https://drive.google.com/file/d/1vCV7X6a1Pp7F7mD4ELtS5hLxRaZ9mcr_/view)

  * **Outreach Assistant**: This volunteer will assist with outreach, sharing
   THRIVE Lifeline as a resource and broadening the impact of the hotline.
   
   * **Resource Manager**: This volunteer will manage the vetting and addition of
   new resources to our database. Estimated 3-6 hours per week.
   [Full Description](https://drive.google.com/file/d/1yKHvWDhegqVUFTdJ4aZa0Hwd5MEFz2MU/view)
   * **Social Media Coordinator**: This volunteer will oversee all social media 
   team members and aid in cross-collaboration between our various platforms 
   as well as organize content development and posting. Estimated 5-8 hours per week.
      [Full Description](https://drive.google.com/file/d/1CPEBocokCRSqq_CBUmf5pcKFsI-JXokS/view)
 --> 
 
Project options include:

   * **Social Media Outreach Project:** A 10-hour project for a volunteer looking to expand THRIVE’s social media presence through connecting with other accounts.
   * **T-Shirt Design Project:** A 5-hour project for a volunteer interested in graphic design. Will use Canva to design a t-shirt that we can sell on our Bonfire store.
   * **Outreach Project:** A 10-hour project for a volunteer interested in sharing THRIVE’s crisis line and volunteer opportunities with people in their community.
   * **Social Media Project:** A 4-, 10-, or 20-hour project for a volunteer interested in designing and creating social media posts in Canva to share on THRIVE’s Instagram, Facebook, and LinkedIn pages.
   * **Social Media Campaign Project:** A 15-hour project for a volunteer interested in outlining a social media campaign for THRIVE.
   * **Fundraising Project:** A 5-hour project for a volunteer interested in helping raise money for THRIVE Lifeline.
   
Other ways to support THRIVE, without filling out a volunteer application:

  * **Share our line within your communities:** We rely on people like you to share our line with others who might need our support. Do you know any online or in-person community spaces which could benefit from a mental health resource for marginalized communities? [Check out this PDF with brief instructions and some templated outreach messages that you can share.](https://drive.google.com/file/d/1P3cVeqHRpvBFrr0gYfaKCOrj1QidfYWn/view?usp=drive_link)
  * **Start a fundraiser for THRIVE on Facebook:** As a grassroots organization, we largely rely on funds from others who are able to donate financially. [Check out this video from one of our volunteers on how to ask for money.](https://www.youtube.com/watch?v=UuKf3mhRO4I)
  * **Print and share our [brochures](https://drive.google.com/file/d/1XJDqey5d-y2v7nPSTI8nwGMmNLlzYXx1/view?usp=drive_link) and [business cards](https://drive.google.com/drive/u/0/folders/185IRJMNA-hbLaXx5NHqifEuWnh11gmy8) with your community**
   
<br>
Volunteer with THRIVE! [**Apply Here**](https://form.jotform.com/201655418668059).
We will reply within 48 hours.

<br>

The calendar below includes all virtual peer support offerings, volunteer orientations, and Peer Supporter trainings.

<center>
**All times are given in the Eastern Time Zone (New York).**

<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23B39DDB&amp;ctz=America%2FNew_York&amp;src=Y192bGRlM285YzVidDU4a2gwM2tuMmI3Y240Y0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%23009688&amp;showCalendars=1&amp;showTabs=1&amp;showTitle=1" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</center>
