name: Build R and do Jekyll site CI

on:
  push:
#    branches: master
  pull_request:
#    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install data tables
        run: Rscript -e 'install.packages("DT")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Render README
        run: Rscript generate-resources.R
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
